# Use the official Nginx base image
FROM nginx:latest

# Copy your custom Nginx configuration into the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose the port that Nginx will listen on
EXPOSE 80
